Have sh_bootstrap

diff --git a/tools/libexec/bootstrap/sh_bootstrap b/tools/libexec/bootstrap/sh_bootstrap
--- a/tools/libexec/bootstrap/sh_bootstrap
+++ b/tools/libexec/bootstrap/sh_bootstrap
@@ -44,16 +44,16 @@
 # pwi 2013- 6-11 creation
 # pwi 2015- 7- 2 update to trychlos.pwi
 # pwi 2017- 6-21 publish the release at last
-# pwi 2021- 5-24 change the bootstrapping process to ttp.d/ *.conf
-# pwi 2025- 2- 7 get the drop-in directory as an argument
+# pwi 2021- 5-24 change the bootstrapping process to ttp.d/*.conf
+# pwi 2025- 2- 7 get the drop-in directory as an argument, have a default value
 
 # Enumerates on stdout path read from conf files for initial TTP addressing
 function f_bootstrap_enumerate_path
 {
-	typeset _dropin="${1}"
-	for _dir in ${_dropin} ${HOME}/.ttp.d; do
+	for _dir in $*; do
+		[ "${VERBOSE}" = "1" ] && echo "[sh_bootstrap] got drop-in: '${_dir}'" 1>&2
 		LANG=C /bin/ls -1 "${_dir}"/*.conf 2>/dev/null | while read _conf; do
-			[ "${VERBOSE}" = "1" ] && echo "[sh_bootstrap] found ${_conf}" 1>&2
+			[ "${VERBOSE}" = "1" ] && echo "[sh_bootstrap] got conf: '${_conf}'" 1>&2
 			grep -vE '^\s*#' "${_conf}"
 		done
 	done
@@ -65,24 +65,35 @@ function f_bootstrap_enumerate_functions
 	echo "bspPathAppendByName bspPathAppendByValue bspPathPrependByName bspPathPrependByValue"
 }
 
-# Loads external functions or emits an error message on stderr
-# Returns an error count
+# Loads external functions if possible
+# Echoes on stdout the list of still not-loaded functions
+bspMissing="ALL"
 function f_bootstrap_load_functions
 {
-	typeset _path="${1}"
-	typeset -i _count=0
-	for _funcread in $(f_bootstrap_enumerate_functions); do
-		typeset _funcfull="${_path}/libexec/sh/${_funcread}"
-		if [ -r "${_funcfull}" ]; then
-			source "${_funcfull}"
-			[ "${VERBOSE}" = "1" ] && echo "[sh_bootstrap] sourcing ${_funcfull}" 1>&2 
-		else
-			echo "[sh_bootstrap] ${_funcfull}: not found or not readable" 1>&2
-			let _count+=1;
-		fi
-	done
-	[ "${VERBOSE}" = "1" ] && echo "[sh_bootstrap] returning ${_count} errors on functions preload" 1>&2
-	return ${_count}
+	typeset _toload="${1}"
+	typeset _path="${2}"
+	typeset _missing=""
+	if [ -z "${_toload}" ]; then
+		echo "[sh_bootstrap] f_bootstrap_load_functions() called while there is nothing left to load" 1>&2
+	else
+		for _funcread in $(f_bootstrap_enumerate_functions); do
+			typeset _done="no";
+			if [ "${_toload}" != "ALL" -a "$(echo "${_toload}" | grep "${_funcread}" 2>/dev/null)" = "" ]; then
+				_done="yes"
+			fi
+			if [ "${_done}" = "no" ]; then
+				typeset _funcfull="${_path}/libexec/sh/${_funcread}"
+				if [ -r "${_funcfull}" ]; then
+					source "${_funcfull}"
+					[ "${VERBOSE}" = "1" ] && echo "[sh_bootstrap] sourcing '${_funcfull}'" 1>&2
+				else
+					_missing="${_missing} ${_funcread}"
+				fi
+			fi
+		done
+	fi
+	[ "${VERBOSE}" = "1" ] && echo "[sh_bootstrap] f_bootstrap_load_functions() for ${_path} returns missing '${_missing}'" 1>&2
+	bspMissing="${_missing}"
 }
 
 # Set PATH and FPATH global environment variables
@@ -91,46 +102,67 @@ function f_bootstrap_setup
 	typeset _prefix="${1}"
 	typeset _path="${2}"
 	if [ "${_prefix}" = "-" ]; then
-		[ "${VERBOSE}" = "1" ] && echo "[sh_bootstrap] prepending ${_path}" 1>&2
-		bspPathPrependByName     PATH "${_path}/bin"
-		bspPathPrependByName    FPATH "${_path}/libexec/sh"
-		bspPathPrependByName PERL5DIR "${_path}/libexec/perl"
+		[ "${VERBOSE}" = "1" ] && echo "[sh_bootstrap] prepending '${_path}'" 1>&2
+		bspPathPrependByName      PATH "${_path}/bin"
+		bspPathPrependByName     FPATH "${_path}/libexec/sh"
+		bspPathPrependByName  PERL5DIR "${_path}/libexec/perl"
+		bspPathPrependByName TTP_ROOTS "${_path}"
 	else
-		[ "${VERBOSE}" = "1" ] && echo "[sh_bootstrap] appending ${_path}" 1>&2
+		[ "${VERBOSE}" = "1" ] && echo "[sh_bootstrap] appending '${_path}'" 1>&2
 		bspPathAppendByName      PATH "${_path}/bin"
 		bspPathAppendByName     FPATH "${_path}/libexec/sh"
-		bspPathPrependByName PERL5DIR "${_path}/libexec/perl"
+		bspPathAppendByName  PERL5DIR "${_path}/libexec/perl"
+		bspPathAppendByName TTP_ROOTS "${_path}"
 	fi
 }
 
 # Main function
+# Enumerate paths until having loaded all functions
+# Re-enumerate to setup our environment variables
 function f_bootstrap
 {
-	typeset _loaded=""
-	for _pathread in $(f_bootstrap_enumerate_path); do
+	typeset _dropins="$@"
+	typeset -i _ret=0
+	for _pathread in $(f_bootstrap_enumerate_path "${_dropins}"); do
 		if [ ! -z "${_pathread}" ]; then
+			[ "${VERBOSE}" = "1" ] && echo "[sh_bootstrap] got path: '${_pathread}'" 1>&2
 			typeset _pathclean="${_pathread}"
 			[ "${_pathread:0:1}" = "-" ] && _pathclean="${_pathread:1}"
-			if [ -z "${_loaded}" ]; then
-				f_bootstrap_load_functions "${_pathclean}"
-				[ $? -eq 0 ] && _loaded="done" || _loaded="tried with errors"
-				[ "${VERBOSE}" = "1" ] && echo "[sh_bootstrap] load functions ${_loaded}"
+			f_bootstrap_load_functions "${bspMissing}" "${_pathclean}"
+			if [ -z "${bspMissing}" ]; then
+				break
 			fi
-			[ "${_loaded}" = "done" ] && f_bootstrap_setup "${_pathread:0:1}" "${_pathclean}"
 		fi
 	done
-	[ "${_loaded}" = "done" ] && return 0 || return 1
+	if [ -z "${_missing}" ]; then
+		for _pathread in $(f_bootstrap_enumerate_path "${_dropins}"); do
+			if [ ! -z "${_pathread}" ]; then
+				[ "${VERBOSE}" = "1" ] && echo "[sh_bootstrap] got path: '${_pathread}'" 1>&2
+				typeset _pathclean="${_pathread}"
+				[ "${_pathread:0:1}" = "-" ] && _pathclean="${_pathread:1}"
+				f_bootstrap_setup "${_pathread:0:1}" "${_pathclean}"
+			fi
+		done
+	else
+		echo "[sh_bootstrap] unable to load '${_missing}' functions" >&2
+		_ret=1
+	fi
+	return ${_ret}
 }
 
-# Ansible interprets anything it find on stderr as a fatal error, and
-#  refuses to connect to the machine
-[ -z "${1}" ] && echo "[sh_bootstrap] expect drop-in directory as argument" 1>&2 && return 1
-f_bootstrap "${1}" && . ttp.sh switch -default 2>&1
+# Ansible interprets anything it finds on stderr as a fatal error, and refuses to connect to the machine
+
+# Have the usual 'HOME/.ttp.d /etc/ttp.d' default values, letting the caller override that
+typeset bspPathList="$@"
+[ -z "${1}" ] && bspPathList=""${HOME}/.ttp.d" "/etc/ttp.d""
+
+f_bootstrap "${bspPathList}" && . ttp.sh switch -default 2>&1
 typeset -i _ret=$?
 
 [ "${VERBOSE}" = "1" ] && echo "[sh_bootstrap] PATH='${PATH}'" 1>&2
 [ "${VERBOSE}" = "1" ] && echo "[sh_bootstrap] FPATH='${FPATH}'" 1>&2
 [ "${VERBOSE}" = "1" ] && echo "[sh_bootstrap] PERL5DIR='${PERL5DIR}'" 1>&2
+[ "${VERBOSE}" = "1" ] && echo "[sh_bootstrap] TTP_ROOTS='${TTP_ROOTS}'" 1>&2
 
-unset $(set | grep -E '^f_|^bspPath') 1>/dev/null 2>&1
+unset $(set | grep -E '^f_|^bspPath|bspMiss') 1>/dev/null 2>&1
 return ${_ret}
